apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmc-prometheus-pv
  labels:
    cmcglobal: cmc
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce # required
  hostPath:
    path: /dataPromCluster
    type: DirectoryOrCreate