apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cmcglobal: ptmduc
  name: prometheus-cluster-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /dataPromCluster
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem