apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cmcglobal: ptmduc
  name: prometheus-cluster-pvc
  namespace: cattle-prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: prometheus-cluster-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound