apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s 
      external_labels:
        monitor: 'codelab-monitor'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['192.168.73.146:9100']
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-kq9kp
  labels:
    cattle.io/creator: norman
  name: prometheus
  namespace: cattle-prometheus