apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-ptmduc
  name: prometheus-ptmduc
  namespace: cattle-prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-ptmduc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-ptmduc
    spec:
      containers:
      - image: prom/prometheus
        imagePullPolicy: Always
        name: prometheus-ptmduc
        ports:
        - containerPort: 9090
          name: metrics
          protocol: TCP
        volumeMounts:
        # - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        #   name: cluster-monitoring-token-bqpj5
        - mountPath: /etc/prometheus
          name: prometheus
        # - mountPath: /etc/prometheus/secrets/exporter-etcd-cert
        #   name: secret-exporter-etcd-cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      # - name: cluster-monitoring-token-bqpj5
      #   secret:
      #     defaultMode: 420
      #     secretName: cluster-monitoring-token-bqpj5
      - configMap:
          defaultMode: 420
          name: prometheus
          optional: false
        name: prometheus
      # - name: secret-exporter-etcd-cert
      #   secret:
      #     defaultMode: 420
      #     optional: false
      #     secretName: exporter-etcd-cert