{
 "title": "JenkinsDU12",
 "tags": [ "DU12 " ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jenkins Jobs  builds health score",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_health_score",
     "legendFormat": "{{ jenkins_job }}"
    },
    {
     "expr": "default_jenkins_builds_last_build_result"
    },
    {
     "expr": "default_jenkins_builds_success_build_count"
    },
    {
     "expr": "default_jenkins_builds_failed_build_count"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "vm_cpu_load" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "expr": "vm_memory_total_used" }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(vm_memory_total_max - vm_memory_total_used) / vm_memory_total_max * 100.0"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "default_jenkins_uptime" }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_health_check_score" }
   ]
  },
  {
   "title": "Processing speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration_count[1m])"
    }
   ]
  },
  {
   "title": "Sucessful Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_success_total" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_failure_total" }
   ]
  },
  {
   "title": "Unstable Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_unstable_total" }
   ]
  },
  {
   "title": "Aborted Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_runs_aborted_total" }
   ]
  }
 ]
}