{
 "title": "Monitor Hardware",
 "tags": [ "DU12" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(node_load1, host_ip)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU System Load Current",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{host_ip=~\"$node\"}) / count(node_cpu_seconds_total{mode=\"system\",host_ip=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Used RAM Memory Current",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{host_ip=~\"^$node\"} * 100) / node_memory_MemTotal_bytes{host_ip=~\"^$node\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\",host_ip=~\"^$node\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{host_ip=~\"^$node\"} - node_boot_time_seconds{host_ip=~\"^$node\"}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{host_ip=~\"^$node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host_ip=~\"^$node\"} - node_memory_MemFree_bytes{host_ip=~\"^$node\"} - (node_memory_Cached_bytes{host_ip=~\"^$node\"} + node_memory_Buffers_bytes{host_ip=~\"^$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{host_ip=~\"^$node\"} + node_memory_Buffers_bytes{host_ip=~\"^$node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{host_ip=~\"^$node\"}",
     "legendFormat": "RAM Available"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(node_load5{host_ip=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{host_ip=~\"^$node\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{host_ip=~\"^$node\",device=~\"[a-z]*[a-z]\"}[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{host_ip=~\"^$node\", device!~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{host_ip=~\"^$node\", device!~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",host_ip=~\"^$node\"})/1024/1024/1024) - (sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",host_ip=~\"^$node\"})/1024/1024/1024)",
     "legendFormat": "Disk space used"
    },
    {
     "expr": "(sum(node_filesystem_free_bytes{device!~\"rootfs|HarddiskVolume.+\",host_ip=~\"^$node\"})/1024/1024/1024)",
     "legendFormat": "Disk space free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{device!~\"rootfs|HarddiskVolume.+\",host_ip=~\"^$node\"})/1024/1024/1024)",
     "legendFormat": "Total disk"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{host_ip=~\"^$node\",device!~'rootfs'} - node_filesystem_avail_bytes{host_ip=~\"^$node\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}