apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: ""
  labels:
    k8s-app: jenkins
    monitoring.coreos.com: "true"
  name: expose-jenkins-metrics
  namespace: cattle-prometheus
subsets:
- addresses:
  - ip: 192.168.67.74
  ports:
  - name: metrics
    port: 8080
    protocol: TCP


